version: "3.7"

services:
  influxdb2:
    container_name: df.influxdb2.docker
    image: influxdb:2.6-alpine
    ports:
      - "${INFLUXDB_PORT}:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB2_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB2_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB2_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB2_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
      - DOCKER_INFLUXDB_INIT_MODE=setup
    volumes:
      - influxdb2-vol:/var/lib/influxdb2
      - influxdb2-config-vol:/etc/influxdb2
      # - ./data/df/:/usr/backups/


volumes:
  influxdb2-vol:
  influxdb2-config-vol: